version: 2

models:
  - name: prspctf_fact_emp_quitter
    description: >
        Table de fait qui liste les employés qui ont quitté et sont susceptibles d'être remplacer

  - name: prspctf_fact_masse_sal_corp_empl
    description: >
        Table de fait qui calcul le salaire moyen par corp d'emploi et masse salariale totale par année budgétaire