version: 2

models:
  - name: prspctf_fact_masse_sal_corp_empl
    description: >
        Table de reporting qui calcul le ratio du coup de roulement sur la masse salariale totale par année budgétaire