version: 2
models:
  - name: stg_absences_scolaires_unpivot
    description: |-
      Table des absences brutes des employés enrichie avec le contexte RH, filtrée pour l'année scolaire et les jours ouvrés. Les absences sont catégorisées et transformées via UNPIVOT pour distinguer les absences de courte durée (CL) et longue durée (DL).
    columns:
      - name: annee
        description: |-
          Année scolaire correspondant à l'absence (ex. '2023-2024').
        tests:
          - not_null
      - name: matricule
        description: |-
          Identifiant unique de l'employé.
        tests:
          - not_null
          - relationships:
              to: ref('dim_employees')
              field: matr
      - name: date_abs
        description: |-
          Date de l'absence.
        tests:
          - not_null
      - name: lieu_trav
        description: |-
          Code du lieu de travail de l'employé.
      - name: pourc_sal
        description: |-
          Pourcentage de salaire de l'employé à la date de l'absence.
      - name: gr_paie
        description: |-
          Groupe de paie de l'employé.
        tests:
          - not_null
      - name: corp_empl
        description: |-
          Code du corps d'emploi de l'employé.
      - name: dure
        description: |-
          Durée de l'absence en unité définie (ex. heures).
      - name: jour_sem
        description: |-
          Jour de la semaine (0=dimanche, 1=lundi,...,6=samedi).
      - name: categorie
        description: |-
          Catégorie d'absence après jointure avec type_absence.
      - name: type_duree
        description: |-
          Type de durée après UNPIVOT : 'dl' = longue durée, 'cl' = courte durée.
        tests:
          - accepted_values:
              values:
                - duree_longue
                - duree_courte
  - name: stg_calendrier_jours_eligibles
    description: |-
      Table des groupes de paie ayant des jours ouvrés admissibles par année budgétaire. Exclut les congés, les jours d’été et les fins de semaine.
    columns:
      - name: annee
        description: |-
          Année budgétaire (champ [an_budg]) utilisée pour agréger les jours travaillés.
        tests:
          - not_null
      - name: gr_paie
        description: |-
          Groupe de paie permettant de segmenter les employés selon leur type d’emploi (ex. enseignant, soutien, cadre).
        tests:
          - not_null
