version: 2

models:
  - name: dim_mapper_schools
    description: >
      Map each school to a friendly name to provide a consistent naming accross dashboards.

      This dimension can be overriden to allow for naming customisation.
    tests:
      - resolution:
          combination_of_columns:
            - annee
            - eco

  - name: dim_eleve
    description: >
      Table listing static information for each student.
    columns:
      - name: fiche
        description: fiche de l'élève
        tests:
          - not_null
          - unique
      - name: code_perm
        description: code permanent de l'élève
        tests:
          - not_null
          - unique

  - name: dim_etapes
    description: >
      This table maps the "étape" calendar to a grouping of students. Identifcation of the students is done through code distribution, groupe repere, ordre enseignement and class.
    columns:
      - name: classe
        tests:
          - not_null
      - name: id_eco
        tests:
          - not_null
      - name: ordre_ens
        tests:
          - not_null
