version: 2

models:
  
  - name: stg_populations_fgj
    config:
      tags:
        - population
        - educ_serv
        - prospectif_cdp    
    description: >
      Table auxilaire de resolution fiche, id_eco et contenant l'assignement d'une fiche à une population pour le calcul de métriques inter-populationelles.
    tests:
      - resolution:
          combination_of_columns:
            - fiche
            - id_eco
            - population

  - name: spine
    config:
      tags:
        - population
        - educ_serv
        - prospectif_cdp  
    description: >
      La table de spine de résolution fiche, id_eco qui contient l'ensemble des numéros de fiches par année scolaire et population.
      Elle permet la construction des tables de faits via l'utilisation de left joins.
      ---
      A spine table of resolution fiche, id_eco. Used as a backbone for all the Prodrome fact tables.
    tests:
      - resolution:
          combination_of_columns:
            - fiche
            - id_eco
            - population
    
  - name: fact_freq_fga
    config:
      tags:
        - population
        - educ_serv
        - prospectif_cdp  
    description: >
      Table qui enregistre l'ensemble des fréquentations FGA. 

  - name: fact_freq_fp
    config:
      tags:
        - population
        - educ_serv
        - prospectif_cdp  
    description: >
      Table qui enregistre l'ensemble des fréquentations FP.
