version: 2

models:
  - name: rstps_dim_subject_evaluation
    description: >
      Table de dimensions mappant à chaque épreuve unique / obligatoire / maison, les codes_matières, les no_competences et les cod_etapes requis.
      La table est constuite en unionant la dimension par défaut (core/seeds/res_etapes/default_subject_evaluation.csv) et la dimension custom (cssss/seeds/res_etapes/custom_subject_evaluation.csv).
      La table `custom` peut-etre adaptée pour chaque CSS pour rajouter des épreuves.

  - name: rstps_fact_evaluations_grades
    description: >
      La table regroupe les notes des matières sujettes à examens. Cette table accumulate à la fois les résultats extrait par le processus automatique basé sur rstps_dim_subject_evaluation et aussi les éventuelles tables customs (to be done.)
  
  - name: rstps_report_evaluation_grades_schools
    description:
      La table calcule des métriques de taux de succès par évaluation (obligatoire ou maison), par établissement et par année.
  
  - name: rstps_report_evaluation_grades
    description:
      La table calcule des métriques de taux de succès par évaluation (obligatoire ou maison) par année, au niveau (aggrégé) du CSS.
  