SELECT 
    id_mat_ele
    , id_mat_grp
    , fiche
    , id_eco
    , mat
    , grp
    , etat
    , res_meq
    , r100_meq
    , unites_ele
    , res_som
    , res_pond_som
    , pond_som
    , res_etape_01
    , res_etape_02
    , res_etape_03
    , res_etape_04
    , res_etape_05
    , res_etape_06
    , res_etape_07
    , res_etape_08
    , res_etape_09
    , res_etape_10
    , res_pond_etape_01
    , res_pond_etape_02
    , res_pond_etape_03
    , res_pond_etape_04
    , res_pond_etape_05
    , res_pond_etape_06
    , res_pond_etape_07
    , res_pond_etape_08
    , res_pond_etape_09
    , res_pond_etape_10
    , type_form_mat
    , rem
    , res_som_etapes
    , res_som_calc
    , jugement
    , reprise
    , modele_etape
    , mois_sanction
FROM {{ var("database_gpi") }}.dbo.gpm_e_mat_ele