version: 2

models:
  - name: fact_absences_sequence
    description: >
      List the sequence of absences for each student.
      A sequence of absences is a set of consecutives school days with at least one absence for each day.
      A sequence of absences is caracterized by its start date, its end date, and the absences in the sequence.
    tests:
      - resolution:
          combination_of_columns:
            - school_year
            - fiche
            - eco
            - absence_sequence_id
            - category_abs

  - name: fact_resultat_bilan_competence
    config:
      tags:
        - res_scolaires
    description: >
      List the competency results of all students
    columns:
      - name: code_perm
        description: Unique ID of the student
      - name: id_eco
        description: Unique ID of the school per year
      - name: annee
        description: The school year
      - name: fiche
        description: Unique ID of the student
      - name: population
        description: Identification of a student within the order of education
      - name: ordre_ens
        description: The order of education
      - name: genre
        description: The gender of the student
      - name: plan_interv_ehdaa
        description: Intervention plan
      - name: niveau_scolaire
        description: The grade of the student
      - name: id_mat_ele
        description: Unique ID of the subject per student per year
      - name: mat
        description: Description of the subject
      - name: grp
        description: The group which the student is related to the subject
      - name: etat
        description: The state of the subject
      - name: is_reprise
        description: Indicate if its a retake
      - name: no_comp
        description: The competency number of the subject
      - name: descr
        description: The description of the subject
      - name: descr_abreg
        description: The description of the subject abbreviated
      - name: res_num_comp
        description: The results of the student per no_comp, per mat
    tests:
      - resolution:
          combination_of_columns:
            - fiche
            - id_eco
            - is_reprise
            - mat
            - no_comp
            - grp

  - name: fact_resultat_bilan_matiere
    config:
      tags:
        - res_scolaires
    description: >
      List the competency results of all students
    columns:
      - name: id_eco
        description: Unique ID of the school per year
      - name: annee
        description: The school year
      - name: fiche
        description: Unique ID of the student
      - name: id_mat_ele
        description: Unique ID of the subject per student per year
      - name: mat
        description: The subject
      - name: grp
        description: The group which the student is related to the subject
      - name: etat
        description: The state of the subject
      - name: is_reprise
        description: Indicate if its a retake
      - name: is_reussite
        description: Indicate if its a success
      - name: res_num_som
        description: The results of the student per mat
    tests:
      - resolution:
          combination_of_columns:
            - fiche
            - id_eco
            - is_reprise
            - mat
            - grp

  - name: fact_resultat_etape_competence
    config:
      tags:
        - res_scolaires
    description: >
      List the result to the subject of all students
    columns:
      - name: annee
        description: The school year
      - name: fiche
        description: Unique ID of the student
      - name: id_eco
        description: Unique ID of the school
      - name: mat
        description: The subject
      - name: grp
        description: The group which the student is related to the subject
      - name: id_obj_mat
        description: The unique ID of the competence which is related to the subject
      - name: no_comp
        description: The competency number of the subject
      - name: etat
        description: The state of the subject
      - name: etape
        description: The stage of the subject
      - name: res_comp_num
        description: The result in numeric
      - name: is_reussite
        description: Indicate if its a success
      - name: is_reprise
        description: Indicate a retake
    tests:
      - resolution:
          combination_of_columns:
            - fiche
            - id_eco
            - etape
            - grp
            - id_obj_mat

  - name: fact_resultat_etape_matiere
    config:
      tags:
        - res_scolaires
    description: >
        List the result of all student
    columns:
      - name: annee
        description: The school year
      - name: fiche
        description: Unique ID of the student
      - name: id_eco
        description: Unique ID of the school
      - name: mat
        description: The subject
      - name: descr
        description: The description of the subject
      - name: grp
        description: The group which the student is related to the subject
      - name: etat
        description: The state of the subject
      - name: etape
        description: The stage of the subject
      - name: res_etape_num
        description: The result in numeric
      - name: is_reussite
        description: Indicate if its a success
      - name: is_reprise
        description: Indicate a retake
    tests:
      - resolution:
          combination_of_columns:
            - fiche
            - id_eco
            - etape
            - grp
            - mat

  - name: fact_yearly_student
    config:
      tags:
        - res_scolaires
    description: >
        Grouping of the spine students including some information used for filters.
    columns:
      - name: code_perm
        description: Unique ID of the student
      - name: id_eco
        description: Unique ID of the school per year
      - name: annee
        description: The school year
      - name: fiche
        description: Unique ID of the student
      - name: population
        description: Identification of a student within the order of education
      - name: eco
        description: The school dedicated number
      - name: code_ecole
        description: The school number concat with the school name
      - name: ordre_ens
        description: The order of education
      - name: niveau_scolaire
        description: The grade of the student
    tests:
      - resolution:
          combination_of_columns:
            - code_perm
            - id_eco
            - annee
            - population
