version: 2

models:
  - name: fact_tps_partial
    tags: ["fact_table"]
    description: >
      Table de faits, de résolution année / ecole, qui comptabilise le nombre d'employés à temps partiel par année et école. 