name: "core_dashboards_store"
version: "0.9.0"
config-version: 2

profile: "nightly_profile" #"Make sure you a runing DBT from the cssXX repository, not the core.dashboards_store repository."

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Hooks : copy thoose hooks into your `cssXX.data.store/dbt_project.yml` file to enable the stamper collection
on-run-start:
  - "{{ core_dashboards_store.init_metadata_table() }}"
on-run-end:
  - "{{ core_dashboards_store.purge_metadata_table() }}"

seeds:
  +tags: ["seeds"]
  core_dashboards_store:
    common:
      +schema: common_seeds
    dashboards:
      educ_serv:
        +tags: ["educ_serv"]
        diplome:
          +tags: ["diplome"]
          +schema: "dashboard_diplome"
        res_epreuves:
          +tags: ["res_epreuves"]
          +schema: "dashboard_res_epreuves"
        suivi_resultats:
          +tags: ["suivi_resultats"]
          +schema: "dashboard_suivi_resultats"
        res_scolaires:
          +tags: ["res_scolaires"]
          +schema: "dashboard_res_scolaires"
        chronic_absenteeism:
          +tags: ["chronic_absenteeism"]
          +schema: "dashboard_chronic_absenteeism"
      other:
        pevr:
          +tags: ["pevr"]
          +schema: "dashboard_pevr"          

models:
  +materialized: table
  core_dashboards_store:
    +enabled: False
    marts:
      human_resources:
        +tags:
          - "human_resources"
          - "mart_human_resources"
        +schema: human_resources
        features:
        staging:
          +schema: human_resources_staging
      educ_serv:
        +tags:
          - "educ_serv"
          - "mart_educ_serv"
        +schema: educ_serv
        features:
        staging:
          +schema: educ_serv_staging

    dashboards:
      educ_serv:
        +tags: ["educ_serv"]
        effectif_css:
          +tags: ["effectif_css"]
          +schema: dashboard_effectif_css
          pbi_tables:
            +post-hook:
              [
                "{{ core_dashboards_store.stamp_model('dashboard_effectif_css') }}",
              ]

        res_epreuves:
          +tags: ["res_epreuves"]
          +schema: "dashboard_res_epreuves"
          pbi_tables:
            +post-hook:
              [
                "{{ core_dashboards_store.stamp_model('dashboard_res_epreuves') }}",
              ]

        suivi_resultats:
          +tags: ["suivi_resultats"]
          +schema: "dashboard_suivi_resultats"
          pbi_tables:
            +post-hook:
              [
                "{{ core_dashboards_store.stamp_model('dashboard_suivi_resultats') }}",
              ]

        res_scolaires:
          +tags: ["res_scolaires"]
          +schema: "dashboard_res_scolaires"
          pbi_tables:
            +post-hook:
              [
                "{{ core_dashboards_store.stamp_model('dashboard_res_scolaires') }}",
              ]

        absenteeism:
          +tags: ["absenteeism"]
          +schema: "dashboard_absenteeism"
          pbi_tables:
            +post-hook:
              [
                "{{ core_dashboards_store.stamp_model('dashboard_absenteeism') }}",
              ]

        chronic_absenteeism:
          +tags: ["chronic_absenteeism"]
          +schema: "dashboard_chronic_absenteeism"
          pbi_tables:
            +post-hook:
              [
                "{{ core_dashboards_store.stamp_model('dashboard_chronic_absenteeism') }}",
              ]

        predictive_view_aggregated:
          +tags: ["predictive_view_aggregated"]
          +schema: "dashboard_predictive_view_aggregated"
          pbi_tables:
            +post-hook:
              [
                "{{ core_dashboards_store.stamp_model('dashboard_predictive_view_aggregated') }}",
              ]

        diplome:
          +tags: ["diplome"]
          +schema: dashboard_diplome
          pbi_tables:
            +post-hook:
              ["{{ core_dashboards_store.stamp_model('dashboard_diplome') }}"]

      human_resources:
        +tags: ["human_resources"]
        emp_conge:
          +tags: ["emp_conge"]
          +schema: dashboard_emp_conge
          pbi_tables:
            +post-hook:
              ["{{ core_dashboards_store.stamp_model('dashboard_emp_conge') }}"]

        emp_actif:
          +tags: ["emp_actif"]
          +schema: dashboard_emp_actif
          pbi_tables:
            +post-hook:
              ["{{ core_dashboards_store.stamp_model('dashboard_emp_actif') }}"]

        retirement:
          +tags: ["retirement"]
          +schema: "dashboard_retirement"
          pbi_tables:
            +post-hook:
              [
                "{{ core_dashboards_store.stamp_model('dashboard_retirement') }}",
              ]
      other:
        pevr:
          +tags: ["pevr"]
          +schema: "dashboard_pevr"
          pbi_tables:
              +post-hook:
                [
                  "{{ core_dashboards_store.stamp_model('dashboard_pevr') }}"
                ]
      org_scolaire:
        anomalies:
          +tags: ["anomalies"]
          +schema: "dashboard_anomalies"
          pbi_tables:
            +post-hook:
              [
                "{{ core_dashboards_store.stamp_model('dashboard_anomalies') }}",
              ]
              
    interfaces:
      +tags: ["interfaces"]
      +materialized: ephemeral
    rls:
      +schema: rls
vars:
  is_context_core: true
  # The source database to pull the data for a css.
  database_paie: "Replace me in the CSS repositery"
  database_gpi: "Replace me in the CSS repositery"
  database_jade: "Replace me in the CSS repositery"
  database_prodrome: "Replace me in the CSS repositery" # Modelling output from the Sciance's models.
  # res_epreuves's dashboard variables:

  interfaces:
    gpi:
      max_etapes: 30
      max_periodes: 20

  marts:
    educ_serv:
      recency:
        years_of_data_absences: 10
        years_of_data_grades: 10

  dashboards:
    res_epreuves:
      cod_css: replacemeplease
