name: 'tbe'
version: '1.0.0'
config-version: 2

profile: "replaceMeInLocals"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    
seeds:
    +enabled: False
    res_etapes:
        +tags: ["res_etapes"]
        +schema: 'res_etapes_seeds'

models:
  +materialized: table
  tbe:
    +enabled: False
    store_template:
        +tags: ["template"]
        +schema: 'store_template'
        adapters:
            +tags:
                - adapters
        features:
            +tags:
                - fact_tables
        spines:
            +schema: store_template_staging
    emp_conge:
        +tags: ["emp_conge"]
        +schema: emp_conge
    prospectif_cdp:
        +tags: ["prospectif_cdp"]
        +materialized: table
        +schema: 'prospectif_cdp'
        adapters:
            +tags:
                - adapters
        features:
            +tags:
                - fact_tables
        spines:
            +schema: prospectif_cdp_staging
        pbi_tables:
            +schema: prospectif_cdp_reporting
            +tags:
                - reporting
    transport:
        +tags: ["transport"]
        +schema: 'transport'
        pbi_tables:
            +schema: transport_reporting 
            +tags:
                - reporting 
    res_etapes:
        +tags: ["res_etapes"]
        +schema: 'res_etapes'
        staging:
            +schema: res_etapes_staging
            +tags:
                - staging            
        pbi_tables:
            +schema: res_etapes_reporting
            +tags:
                - reporting
    shared:
        +tags: shared
        +schema: 'shared'
        bridges:
            +schema: shared_staging
        interfaces:
            +materialized: ephemeral

vars:
    # Toggle the adapaters table to the sources tables. To run the package in standalone.
    is_context_core: true
    # The source database to pull the data for a css.
    database_bi: "Replace me in the CSS repositery"
    database_paie: "Replace me in the CSS repositery"
    database_gpi: "Replace me in the CSS repositery"
    database_jade: "Replace me in the CSS repositery"
    database_geobus: "Replace me in the CSS repositery" # contains routes, buses, contractors, student files, and related to db GPL. 
    database_piastre: "Replace me in the CSS repositery" # financial data on school transport. no connections to db Geobus.
    # res_etapes's dashboard variables:
    res_etapes:
        threshold: 70
        cod_css: "Replace me in the CSS repositery"