name: 'pevr'
version: '1.0.0'
config-version: 2

profile: "{{ env_var('DBT_PROFILE', 'cssvdc_pevr') }}"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
    pevr:
        +materialized: table
        adapters:
            +tags:
                - adapters
            +materialized: ephemeral
        spines:
            +schema: staging

vars:
    # Toggle the adapaters table to the sources tables. To run the package in standalone.
    is_context_core: true
    # The source database to pull the data for a css.
    source_database: "[192.168.207.115].[BI_DISTRIBUTION]"
    database_cbm: "[192.168.207.153].[JADEFGFPCVILLE]"
    database_crif: "[192.168.207.153].[JADECRIF]"
    # The default schema to use
    source_schema: dbo