name: 'tbe'
version: '1.0.0'
config-version: 2

profile: "replaceMeInLocals"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  tbe:
    store_template:
        +enabled: False
        +materialized: table
        adapters:
            +tags:
                - adapters
            +materialized: ephemeral
        bridges:
            +schema: staging
        interfaces:
            +tags:
                - interface
            +materialized: ephemeral
        spines:
            +schema: staging

    prospectif_cdp:
        +enabled: False
        +materialized: table
        adapters:
            +tags:
                - adapters
            +materialized: ephemeral

vars:
    # Toggle the adapaters table to the sources tables. To run the package in standalone.
    is_context_core: true
    # The source database to pull the data for a css.
    database_bi: "Replace me in the CSS repositery"
    database_paie: "Replace me in the CSS repositery"
    source_schema: dbo
    # The default schema to use
    source_schema: dbo