name: "store"
version: "0.3.0"
config-version: 2

profile: "replaceMeInLocals"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

# Hooks
on-run-start:
    - "{{ store.init_metadata_table() }}"

seeds:
    +tags: ["seeds"]
    store:
        common:
            +schema: common_seeds
        dashboards:
            prospectif_cdp:
                +tags: ["prospectif_cdp"]
                +schema: "dashbaord_prospectif_cdp"
            res_epreuves:
                +tags: ["res_epreuves"]
                +schema: "dashboard_res_epreuves"
            suivi_resultats:
                +tags: ["suivi_resultats"]
                +schema: "dashboard_suivi_resultats"
models:
    +materialized: table
    store:
        +enabled: False
        meta:
            +enabled: true
            +schema: metadata
            +tags: ["metadata"]
            +materialized: view # Create it as a view so the execution order of the models does not matter
        marts:
            human_resources:
                +tags: ["human_resources"]
                +schema: human_resources
                features:
                staging:
                    +schema: human_resources_staging
            educ_serv:
                +tags: ["educ_serv"]
                +schema: educ_serv
                features:
                staging:
                    +schema: educ_serv_staging

        dashboards:
            effectif_css:
                +tags: ["effectif_css"]
                +schema: dashboard_effectif_css
                pbi_tables:
                    +post-hook:
                        ["{{ store.stamp_model('dashboard_effectif_css') }}"]

            emp_conge:
                +tags: ["emp_conge"]
                +schema: dashboard_emp_conge
                pbi_tables:
                    +post-hook:
                        ["{{ store.stamp_model('dashboard_emp_conge') }}"]

            emp_actif:
                +tags: ["emp_actif"]
                +schema: dashboard_emp_actif
                pbi_tables:
                    +post-hook:
                        ["{{ store.stamp_model('dashboard_emp_actif') }}"]

            prospectif_cdp:
                +tags: ["prospectif_cdp"]
                +schema: "dashbaord_prospectif_cdp"
                pbi_tables:
                    +post-hook:
                        ["{{ store.stamp_model('dashbaord_prospectif_cdp') }}"]

            transport:
                +tags: ["transport"]
                +schema: "dashboard_transport"
                pbi_tables:
                    +post-hook:
                        ["{{ store.stamp_model('dashboard_transport') }}"]

            res_epreuves:
                +tags: ["res_epreuves"]
                +schema: "dashboard_res_epreuves"
                pbi_tables:
                    +post-hook:
                        ["{{ store.stamp_model('dashboard_res_epreuves') }}"]

            suivi_resultats:
                +tags: ["suivi_resultats"]
                +schema: "dashboard_suivi_resultats"
                pbi_tables:
                    +post-hook:
                        ["{{ store.stamp_model('dashboard_suivi_resultats') }}"]

            retirement:
                +tags: ["retirement"]
                +schema: "dashboard_retirement"
                pbi_tables:
                    +post-hook:
                        ["{{ store.stamp_model('dashboard_retirement') }}"]

        interfaces:
            +tags: ["interfaces"]
            +materialized: ephemeral
        rls:
            +schema: rls
vars:
    # The source database to pull the data for a css.
    database_bi: "Replace me in the CSS repositery"
    database_paie: "Replace me in the CSS repositery"
    database_gpi: "Replace me in the CSS repositery"
    database_jade: "Replace me in the CSS repositery"
    database_geobus: "Replace me in the CSS repositery" # contains routes, buses, contractors, student files, and related to db GPL.
    database_piastre: "Replace me in the CSS repositery" # financial data on school transport. no connections to db Geobus.
    # res_epreuves's dashboard variables:
    res_epreuves:
        threshold: 70
        cod_css: "Replace me in the CSS repositery"
    emp_actif:
        nbrs_sem_dern_paie: 1
