name: 'tbe'
version: '0.1.0'
config-version: 2

profile: "replaceMeInLocals"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    
seeds:
    +tags: ["seeds"]
    tbe: 
        dashboards:
            prospectif_cdp:
                +tags: ["prospectif_cdp"]
                +schema: 'prospectif_cdp_seeds'
models:
  +materialized: table
  tbe:
    +enabled: False
    marts:
        human_resources:
            +tags: ["human_resources"]
        educ_serv:
            +tags: ["educ_serv"]
            spines:
                staging:
                    +schema: educ_serv_staging
    dashboards: 
        emp_conge:
            +tags: ["emp_conge"]
            +schema: emp_conge

        emp_actif:
            +tags: ["emp_actif"]
            +schema: emp_actif   
            pbi_tables:
                +schema: emp_actif_reporting
                +tags:
                    - reporting     
              
        prospectif_cdp:
            +tags: ["prospectif_cdp"]
            +materialized: table
            +schema: 'prospectif_cdp'
            adapters:
                +tags:
                    - adapters
            features:
                +tags:
                    - fact_tables
            spines:
                +schema: prospectif_cdp_staging
            pbi_tables:
                +schema: prospectif_cdp_reporting
                +tags:
                    - reporting
        transport:
            +tags: ["transport"]
            +schema: 'transport'
            pbi_tables:
                +schema: transport_reporting 
                +tags:
                    - reporting
            dimensions:
                +schema: transport_dimensions
                +tags:
                    - dimensions
            features:
                +tags:
                    - fact_tables

        res_epreuves:
            +tags: ["res_epreuves"]
            +schema: 'res_epreuves'
            staging:
                +schema: res_epreuves_staging
                +tags:
                    - staging            
            pbi_tables:
                +schema: res_epreuves_reporting
                +tags:
                    - reporting
        suivi_resultats:
            +tags: ["suivi_resultats"]
            +schema: 'suivi_resultats'
            staging:
                +schema: suivi_resultats_staging
                +tags:
                    - staging            
            pbi_tables:
                +schema: suivi_resultats_reporting
                +tags:
                    - reporting
    interfaces:
        +materialized: ephemeral
    rls:
        +schema: rls
vars:
    # Toggle the adapaters table to the sources tables. To run the package in standalone.
    is_context_core: true
    # The source database to pull the data for a css.
    database_bi: "Replace me in the CSS repositery"
    database_paie: "Replace me in the CSS repositery"
    database_gpi: "Replace me in the CSS repositery"
    database_jade: "Replace me in the CSS repositery"
    database_geobus: "Replace me in the CSS repositery" # contains routes, buses, contractors, student files, and related to db GPL. 
    database_piastre: "Replace me in the CSS repositery" # financial data on school transport. no connections to db Geobus.
    # res_epreuves's dashboard variables:
    res_epreuves:
        threshold: 70
        cod_css: "Replace me in the CSS repositery"
    emp_actif:
        nbrs_sem_dern_paie: 1