
version: 2

models:
  - name: fact_tps_partial
    description: >
      Table de faits, de résolution année / ecole, qui comptabilise le nombre d'employés à temps partiel par année et école.  
  - name: fact_permanence
    config:
      tags:
        - rh_permanence    
    description: >
      Table qui enregistre l'ensemble des employés actifs avec l'état de leur permanence. 
      Il est entendu ici que la permanence est une période de deux ans, soit à partir de la date de début du poste actuel 
      ou d'un poste dans le même groupe d'emploi et la date courrante et ce sans cessation d'emploi.
    tests:
      - resolution:
          combination_of_columns:
            - matricule
            - corps_emploi
            - permanence

  - name: fact_retirement
    description: >
      This table list all the employees that are retired and provide metadata at the time of their retirement.
      Provided metadata allow for drill-down by engagement status, workplace, job category, and employment status.
    config:
      tags:
        - retirement
    columns:
      - name: matr
        tests:
          - unique
          - not_null

  - name: fact_retirement_forecasts
    description: >
      This table combine the survival curves with the list of actives employees to get an estimation of the number of employees that will retire in the future, up to 5 years.
      The forecasts are done by job category
    config:
      tags:
        - retirement
    tests:
      - resolution:
          combination_of_columns:
            - school_year
            - job_group_category

  - name: fact_active_employes
    description: > 
      This table list all the active employees and provide metadata at the time of the ETL's run.
    tests:
      - resolution:
          combination_of_columns:
            - matr
