version: 2

models:
  - name: i_pai_dos
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'pai_dos' de la base de données source.