version: 2
models:
  - name: custom_fgj_populations
    config:
      tags:
        - population
        - educ_serv
    description: |-
      This table is a placeholder to be overrded to add custom population definitions. Every populations defined here will be added to the stg_populations_fgj table.
    tests:
      - core_dashboards_store.resolution:
          combination_of_columns:
            - code_perm
            - id_eco
            - annee
            - population
