
version: 2

models:
  - name: fact_tps_partial
    description: >
      Table de faits, de résolution année / ecole, qui comptabilise le nombre d'employés à temps partiel par année et école.  
  - name: fact_permanence
    config:
      tags:
        - human_ressources
        - rh_permanence    
    description: >
      Table qui enregistre l'ensemble des employés actifs avec l'état de leur permanence. 
      Il est entendu ici que la permanence est une période de deux ans, soit à partir de la date de début du poste actuel 
      ou d'un poste dans le même groupe d'emploi et la date courrante et ce sans cessation d'emploi.
    tests:
      - resolution:
          combination_of_columns:
            - matricule
            - corps_emploi
            - permanence