version: 2

models:
  - name: target_geobus_parc
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une parcur actif de actives de la table GEO_P_PARC de la base de données source.
