version: 2
models:
  - name: dim_cal_eco_grid
    description: |-
      Compute the number of periods per grid. Can be overridden by the user to adjust the grid or the number of periods for a given school, or to exclude some schools from the computation.
    tests:
      - resolution:
          combination_of_columns:
            - id_eco
            - date_evenement
            - grille
