{{ cookiecutter.css_short_name + '_store' }}:
  target: dev
  outputs:
    dev:
      # Configure Database access
      type: sqlserver
      driver: "ODBC Driver 17 for SQL Server"
      server: {{ cookiecutter.server_ip }}
      port: {{ cookiecutter.server_port }}
      database: store_dev
      schema: {{ cookiecutter.author }}
      user: {{ cookiecutter.author }}
      password: {{ cookiecutter.db_password }}
      trust_cert: True
      threads: 1
    prod:
      type: sqlserver
      driver: "ODBC Driver 17 for SQL Server"
      server: {{ cookiecutter.server_ip }}
      port: {{ cookiecutter.server_port }}
      database: store
      schema: {{ cookiecutter.author }}
      user: {{ cookiecutter.author }}
      password: {{ cookiecutter.db_password }}
      trust_cert: True
      threads: 1
