name: "nightly_store"
version: "0.0.1"
config-version: 2

profile: "nightly_profile"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ core_dashboards_store.init_metadata_table() }}"
on-run-end:
  - "{{ core_dashboards_store.purge_metadata_table() }}"

tests:
  core_dashboards_store:
    marts:
      educ_serv:
        dimensions:
          +severity: warn

models:
  core_dashboards_store:
    +enabled: True

vars:
  # The source database to pull the data for a css.
  database_paie: "[192.168.207.153].[PAIE]"
  database_gpi: "[192.168.207.153].[GPIPRIM]"
  database_jade: "[192.168.207.153].[JADE]"
  database_prodrome: PBIRS

  is_context_core: false

  res_epreuves:
    cod_css: 866%
    threshold: 70
