name: "nightly_store"
version: "0.0.1"
config-version: 2

profile: "nightly_profile"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ core_dashboards_store.init_metadata_table() }}"
on-run-end:
  - "{{ core_dashboards_store.purge_metadata_table() }}"

tests:
  +pre-hook:
    - "{{ core_dashboards_store.drop_tmp_table_for_current_model(model_name=this.name) }}" # Cleanup all temps table related to the model being run before actually running the model.
  core_dashboards_store:
    marts:
      educ_serv:
        dimensions:
          +severity: warn

models:
  +pre-hook:
    - "{{ core_dashboards_store.drop_tmp_table_for_current_model(model_name=this.name) }}" # Cleanup all temps table related to the model being run before actually running the model.
  core_dashboards_store:
    +enabled: True

vars:
  # The source database to pull the data for a css.
  database_paie: "[192.168.207.153].[PAIE]"
  database_gpi: "[192.168.207.153].[GPIPRIM]"
  database_jade: "[192.168.207.153].[JADE]"
  database_prodrome: PBIRS

  is_context_core: false

  interfaces:
    gpi:
      max_etapes: 30
      max_periodes: 20

  dashboards:
    res_epreuves:
      cod_css: 866%

  marts:
    educ_serv:
      recency:
        years_of_data_absences: 3
        years_of_data_grades: 3
