version: 2

models:
  - name: i_e_ele
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'E_Ele' de la base de données source.

  - name: i_e_freq
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'E_Freq' de la base de données source.

  - name: i_t_prog
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'T_Prog' de la base de données source.

  - name: i_t_wl_descr
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'WL_Descr' de la base de données source.