select
    codeperm,
    fiche as fiche,
    nomariane as nom,
    pnomlegal as prenom,
    ecocenoff as ecole,
    matcharl as matiere,
    anneesanct as annee_resultat,
    moissanct as mois_resultat,
    dateobtensionres as date_resultat,
    grpcharl as groupe,
    resecobrute as res_eco_brute,
    resecomod as res_eco_mod,
    resoffbrute as res_off_brute,
    resoffconv as res_off_conv,
    resofffinal as res_off_final,
    annee as annee,
    typeformcharl as type_form_charl,
    secteurenseignfreq as secteur_enseign_freq
from {{ var("database_jade") }}.dbo.e_ri_resultats
