version: 2

models:
  - name: i_e_ele
    tags: 
      - interface
      - educ_serv
      - prospectif_cdp
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'E_Ele' de la base de données source.

  - name: i_t_prog
    tags: 
      - interface
      - educ_serv
      - prospectif_cdp
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'T_Prog' de la base de données source.

  - name: i_t_wl_descr
    tags: 
      - interface
      - educ_serv
      - prospectif_cdp
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'WL_Descr' de la base de données source.

  - name: i_e_ri_resultats
    tags: 
      - interface
      - educ_serv
      - prospectif_cdp
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'E_RI_Resultats' de la base de données source.
