version: 2

models:
  - name: utilisateurs_ecoles
    tags: ["rls"]
    description: >
      Table utilisée uniquement pour avoir les directeurs, directrices, enseignant(e)s et les écoles.
    tests: 
      - resolution: 
          combination_of_columns: 
            - CompteAuthentification
            - Ecole
    columns:
      - name: CompteAuthentification
        tests: 
            - not_null
      - name: Ecole
        tests: 
            - not_null            
