version: 2

models:
  - name: utilisateurs_ecoles
    tags: ["rls"]
    description: >
      Table utilisée uniquement pour avoir les directeurs, directrices, enseignant(e)s et les écoles.
    tests: 
      - resolution: 
          combination_of_columns: 
            - compte_authentification
            - Ecole
    columns:
      - name: compte_authentification
        tests: 
            - not_null
      - name: Ecole
        tests: 
            - not_null            
  - name: enseignants_secondaire
    tags: ["rls"]
    description: >
      Table utilisée uniquement pour avoir les enseignants du secondaire, leurs écoles et les cours_groupes.
    tests: 
      - resolution: 
          combination_of_columns: 
            - compte_authentification
            - code_ecole
            - cours_groupe
    columns:
      - name: compte_authentification
        tests: 
            - not_null
      - name: code_ecole
        tests: 
            - not_null            
      - name: cours_groupe
        tests: 
            - not_null            
  - name: enseignants_primaire_tuteurs
    tags: ["rls"]
    description: >
      Table utilisée uniquement pour avoir les enseignants du primaire et les tuteurs, leurs écoles et les groupes les liant aux élèves.
    tests: 
      - resolution: 
          combination_of_columns: 
            - adr_electr
            - code_ecole
            - grp_rep
    columns:
      - name: adr_electr
        tests: 
            - not_null
      - name: code_ecole
        tests: 
            - not_null    
      - name: grp_rep
        tests: 
            - not_null   
  - name: eleve_groupes
    tags: ["rls"]
    description: >
      Table utilisée uniquement pour avoir les élèves et les groupes les liant aux enseignants.
    tests: 
      - resolution: 
          combination_of_columns: 
            - fiche
            - cours_groupe
    columns:
      - name: fiche
        tests: 
            - not_null

