version: 2

seeds:
  - name: etat_empl
    description: >
      A mapping table between the employees status and arbitray meta-datas such as the description of the status, the status of the employee (active or not), the status of the employee (on leave or not), the status of the employee (on leave with pay or not), the status of the employee (on leave without pay or not).
      The code to be poppulated are the ones we can find in the i_paie_hemp.etat column.
    columns:
      - name: etat_empl
        description: The codified representation of the etat_employe.
        tests:
          - not_null
      - name: descr
        description: The description of the etat_employe.
        tests:
          - not_null
      - name: etat_actif
        description: Is the code identifiing a currently active employee ?
        tests:
          - not_null
      - name: empl_retr
        description: Is the code identifiing a currently retired employee ?
        tests:
          - not_null
      - name: empl_cong
        description: Is the code identifiing a currently on leave employee ?
        tests:
          - not_null
      - name: cong_lt
        description: Is the code identifiing a currently on long-terme leave employee ?
        tests:
          - not_null
      - name: valid_from
        description: >
          The YEAR (integer) from which the status starts to be valid. The lower bound is included
          If not populated, the status is valid from the 1950 year.
      - name: valid_until
        description: >
          The YEAR (integer) from which the status stops to be valid. The upper bound is excluded from the validity period.
          If not populated, the status is valid until the current year + 1 .
                - name: valid_until
      - name: empl_resi
        description: Is the code identifiing a currently resignation employee ?

    config:
      tags:
        - human_resources
      schema: human_resources_seeds
      column_types:
        etat_empl: nvarchar(3)
        descr: nvarchar(50)
        empl_retr: bit
        empl_cong: bit
        cong_lt: bit
        etat_actif: bit
        valid_from: int
        valid_until: int
        empl_resi: bit


  - name: stat_eng
    description: >
      A mapping table between the employees status and arbitray meta-datas such as the description of the status, the status of the employee (active or not), the status of the employee (on leave or not), the status of the employee (on leave with pay or not), the status of the employee (on leave without pay or not).
      The code to be poppulated are the ones we can find in the i_paie_hemp.etat column.
    columns:
      - name: stat_eng
        description: The codified representation of the etat_employe.
        tests:
          - not_null
      - name: descr
        description: The description of the etat_employe.
        tests:
          - not_null
      - name: is_reg
        description: Is the job satisfies the `regular` definition of a job ?
        tests:
          - not_null
      - name: valid_from
        description: >
          The YEAR (integer) from which the status starts to be valid. The lower bound is included
          If not populated, the status is valid from the 1950 year.
      - name: valid_until
        description: >
          The YEAR (integer) from which the status stops to be valid. The upper bound is excluded from the validity period.
          If not populated, the status is valid until the current year + 1 .
    config:
      tags:
        - human_resources
      schema: human_resources_seeds
      column_types:
        stat_eng: nvarchar(3)
        descr: nvarchar(25)
        is_reg: bit
        valid_from: int
        valid_until: int
