version: 2
models:
  - name: dim_employees
    description: |-
      Provides employee-level static information.
    columns:
      - name: matr
        description: |-
          The unique identifier of an employee.
        tests:
          - unique
      - name: sex
        description: |-
          The sex of an employee.
      - name: sex_friendly_name
        description: |-
          The sex of an employee
      - name: legal_name
        description: |-
          The legal name of the employee
      - name: birth_date
        description: |-
          The birth date of the employee
      - name: email_address
        description: |-
          The email address of an employee
      - name: last_pay_date
        description: |-
          The last pay date of an employee
