version: 2

models:
  - name: fact_eleve
    tags: ["fact_table"]
    description: >
      Table de faits, de résolution fiche / année, qui identifie l'ensemble des élèves inscrits ces 10 dernieres années. 
    tests:
      - resolution:
          combination_of_columns:
            - fiche
            - annee