name: {{ cookiecutter.css_short_name + '_store' }}
profiles: {{ cookiecutter.css_short_name + '_store' }}

version: "1.0.0"
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

{% raw %}
on-run-start:
  - "{{ store.init_metadata_table() }}"
on-run-end:
  - "{{ store.purge_metadata_table() }}"
{% endraw %}

models:
  store:
    marts:
      human_resources:
        +enabled: False
      educ_serv:
        +enabled: False

    dashboards:
      effectif_css:
        +enabled: False
      emp_conge:
        +enabled: False
      emp_actif:
        +enabled: False
      prospectif_cdp:
        +enabled: False
      res_epreuves:
        +enabled: False
      res_scolaires:
        +enabled: False
      suivi_resultats:
        +enabled: False
      transport:
        +enabled: False
      retirement:
        +enabled: False
      chronic_absenteeism:
        +enabled: False
      predictive_view_aggregated:
        +enabled: False
  
    interfaces:
      +tags: ["interfaces"]
      +materialized: ephemeral
      bi_distribution:
        +enabled: False
      paie:
        +enabled: False
      gpi:
        +enabled: False
      jade:
        +enabled: False
      geobus:
        +enabled: False
      prodrome:
        +enabled: False

    rls:
      +enabled: false
    +materialized: table

vars:
  # As the code is excuted from the inherited repo, sources schould behave as if there were refs.
  is_context_core: false

  # The source database to pull the data for a css.
  database_bi: "[{{ cookiecutter.server_ip }}].[BI_DISTRIBUTION]"
  database_paie: "[{{ cookiecutter.server_ip }}].[PAIE]"
  database_gpi: "[{{ cookiecutter.server_ip }}].[GPIPRIM]"
  database_cbm: "[{{ cookiecutter.server_ip }}].[JADEFGFPCVILLE]"
  database_crif: "[{{ cookiecutter.server_ip }}].[JADECRIF]"
  database_jade: "[{{ cookiecutter.server_ip }}].[JADE]"
  database_geobus: "[{{ cookiecutter.server_ip }}].[GEOBUS]"
  database_prodrome: "[{{ cookiecutter.server_ip }}].[PRODROME]"

  res_epreuves:
    cod_css: <cssRegex>
