version: 2

sources:
  - name: employees_status
    description: > 
      Identification of the status of employees through codes, code description, filtering by groups. 
      Seeds are using in the perspective dashboard to identify employees who hold a permanent position and are currently on vacation or employees who are at retirement age
    tags: ["prospectif_cdp"]
    schema: "{{ target.schema }}_prospectif_cdp_seeds"
    tables:
      - name: cstmrs_stat_eng
        description: >
          engagement status csv file. Determines the full or partial employment of the employee and whethe it's a permanant or temporary position
        columns: 
          - name: stat_eng
            description: code of an engagement status,
          - name: stat_descr
            description: descriptions of stat_eng, 
          - name: stat_st
            description: filterong for general status groups, where 1 - permanant position , 0 - temporary position,

  - name: populations
    description: >
      Les populations identifient des regroupement d'étudiants aux profils cohérents, tels que les élèves réguliers ou les élèeves en FGA.
    tags: ["population", "educ_serv"]
    schema: "{{ target.schema }}_educ_serv_staging"
    tables:
      - name: educ_serv_stg_el_prescolaire
        description: >
          Identification de la population en maternelle 4 ans / passe partout / maternelle 5 ans.
        columns:
          - name: fiche
            description: The specific fiche for a student
          - name: id_eco
            description: unique identifier of a school for a given year
          - name: annee
            description: The years the student was active

      - name: educ_serv_stg_el_primaire_reg
        description: >
          Identification de la population au primaire avec un profil régulier.
        columns:
          - name: fiche
            description: The specific fiche for a student
          - name: id_eco
            description: unique identifier of a school for a given year
          - name: annee
            description: The years the student was active

      - name: educ_serv_stg_el_primaire_adapt
        description: >
          Identification de la population au primaire inscrits en adaptation scolaire.
        columns:
          - name: fiche
            description: The specific fiche for a student
          - name: id_eco
            description: unique identifier of a school for a given year
          - name: annee
            description: The years the student was active

      - name: educ_serv_stg_el_sec_reg
        description: >
          Identification de la population au secondaire avec un profil régulier.
        columns:
          - name: fiche
            description: The specific fiche for a student
          - name: id_eco
            description: unique identifier of a school for a given year
          - name: annee
            description: The years the student was active

      - name: educ_serv_stg_el_sec_adapt
        description: >
          Identification de la population au secondaire en adaptation scolaire.
        columns:
          - name: fiche
            description: The specific fiche for a student
          - name: id_eco
            description: unique identifier of a school for a given year
          - name: annee
            description: The years the student was active
