version: 2

sources:
  - name: populations
    description: >
      Les populations identifient des regroupement d'étudiants aux profils cohérents, tels que les élèves réguliers ou les élèeves en FGA.
    tags: ["population", "local_override"]
    schema: "{{ target.schema }}_staging"
    tables:
      - name: stg_pop_test
        description: >
          Identification grossière des eleves du css à des fin d'entrainement.

  - name: interfaces
    tags: ["interface", "local_override"]
    schema: "{{ target.schema }}"
    tables:
      - name: i_pai_dos
