# Only used as a reference. TODO: replace with Pydantic model
css_name: "cssName"
schedule:
  staging: "0 5 * * 1-5" # Every weekday at 7am
  master: "0 10 * * 5" # Every Friday at 10am
timeout: 600
concurrency: 2
docker_url: "unix://var/run/docker.sock"
onepassword_url: "http://op-connect-api:8080"
teams_webhook:
  sciance: "https://stratemia.webhook.office.com/webhookb2/41a12230-17f1-4d6b-96f5-9ffc01c622d5@72f3ee62-86b1-46d4-928d-0a988f5aad48/IncomingWebhook/be3899ea57954ec3948938716e6d9cea/9dff948c-89f6-4006-ab74-d337fe7b3c21"
  client: MaybeMaybeMaybe
