version: 2

models:
  
  - name: prspctf_dim_mat_selct
    description: >
      Table qui mappe chaque matière séléctionnée le code matière, le nom de la matière et le niveau scolaire.
      La table est constuite en faisant une union de la dimension par défaut (core/seeds/prospectif_cdp/res_matieres/default_code_matiere.csv) et la dimension custom (cssss/seeds/prospectif_cdp/res_matieres/custom_code_matiere.csv).
      La table `custom` peut-etre adaptée pour chaque CSS pour rajouter des épreuves. 

  - name: prspctf_fact_anc_2y
    description: >
      Table qui calcul le nombre total d'employé qui ont fait au minimum 2 ans d'ancienneté.
      Elle sert de point d'entré à la table 'prspctf_ratio_anc'
    
  - name: prspctf_fact_demission
    description: >
      Table qui calcul le nombre d'employé ayant démissionné volontairement entre la période du 1er juillet au 30 juin.
      Elle sert de point d'entré à la table 'prspctf_taux_fidelite'

  - name: prspctf_fact_rslt_mat_select
    description: >
      La table regroupe les notes des matières sélectionnées dans le cadre de l'indicateur lié aux résultats scolaire. 
      Cette table accumule les résultats pour les matières identifées dans 'prspctf_dim_mat_selct'.
      Elle sert de point d'entrée à la table 'prspctf_nb_ele_plus_de_66'.

  - name: prspctf_ratio_anc
    description: >
      Table qui fait un ratio entre le nombre d'employé avec 2 ans d'ancienneté sur le total de nombre d'employé par année

  - name: prspctf_taux_fidelite
    description: >
      Table qui fait la ratio sur le nombre d'employé démissioné volontairement par rapport au nombre d'employé total. 

  - name: prspctf_nb_el_fgj
    description: >
      Table qui comptabilise le nombre d'élèves inscrits en FGJ chaque année par école. 

  - name: prspctf_nb_el_fga
    description: >
      Table qui comptabilise le nombre d'élèves inscrits en FGA chaque année par centre. 

  - name: prspctf_nb_el_fp
    description: >
      Table qui comptabilise le nombre d'élèves inscrits en FP chaque année par centre. 

  - name: prspctf_nb_ele_plus_de_66
    description: >
      La table regroupe les notes des matières sélectionnées. Cette table calcul la proportion des élèves ayant eu plus de 66% aux matière sélectionnées et ce pour chaque année