version: 2

models:
  - name: stg_dim_absences_retards_inclusion
    description: >
      Ancillary table selecting the absences and retards reasons you wan't to include in the computation.
    tests:
      - resolution:
          combination_of_columns:
            - id_eco
            - motif_abs
    columns:
      - name: category_abs
        tests:
          - not_null
