version: 2

models:
  - name: i_piastre
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'i_piastre___' de la base de données tbe_dev.