version: 2

models:
  - name: dim_calendrier
    description: Fournit le nombre de jours ouvrables restants par année budgétaire et groupe de paie.
    columns:
      - name: annee
        description: annee est l'année budgétaire utilisée dans la paie
        tests:
          - not_null
      - name: gr_paie
        description: gr_paie est le groupe de paie de l'employé(e)
        tests:
          - not_null          
      - name: date_jour
        description: date_jour est la date d’un jour donné du calendrier
        tests:
          - not_null          
      - name: bal_jour_ouv
        description: bal_jour_ouv est la balance des jours ouvrables
        tests:
          - not_null          
      - name: filter_key
        description: filter_key est un identifiant unique pour une combinaison donnée de modèle, cible et catégorie.
        tests:
          - not_null          
