etl_profile:
  target: staging
  outputs:
    staging:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{ env_var('DBT_SERVER') }}"
      port: "{{ env_var('DBT_PORT') | int }}" 
      database: "{{ env_var('DBT_STAGING') }}"
      schema: dbo
      user: "{{ env_var('DBT_USERNAME') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      trust_cert: True
    master:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{ env_var('DBT_SERVER') }}"
      port: "{{ env_var('DBT_PORT') | int }}" 
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: dbo
      user: "{{ env_var('DBT_USERNAME') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      trust_cert: True