version: 2

models:
  - name: i_geo_p_parc
    tags: ["interface"]
    description: >
      Table d'interface. liste des parcours et connexion avec circuit_id (second_key)
  - name: i_geo_p_circ
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une list des  cercuites et la connection with nomer contractors
  