version: 2

models:
  - name: prspctf_rprt_emp_ge55_ann_bdgtr
    description: >
        This table exposes the proportion of permanent employees reaching 55 years or more all over the total number of permanent employees for a given fiscal year.
    columns:
      - name: annee_budgetaire
        description: The fiscal year the datas belong to.
      - name: number_of_permanent_employee
        description: The number of permanent employee
      - name: number_of_permanent_employee_ge55_years_old
        description: The number of permanent employee reaching 55 years or more during the fiscale year.
      - name: proportion_of_permanent_employee_ge55_years_old
        description: The proportion of permanent employee reaching 55 years or more years old during the fiscale year over the total number of permanent employee.
